### ISSUE TITLE
Discussion: data privacy

### ISSUE THREAD

**Issue by AnandBaburajan** [RocketMeet/RocketMeet-client#106]
Presently all the data: the meeting name, times and participants' names are stored in our database. Is there a solution to this? I think we could let Google store their data via Calendar, but not sure what's best for the users. https://twitter.com/dan_abramov/status/1369500909789675520 haha.

**Comment by AnshMishra2001** [comment]
Can I work on this issue?

**Comment by AnandBaburajan** [comment]
> Can I work on this issue?

Hey @AnshMishra2001! Thanks! This is a discussion so you can suggest your ideas and solutions. You're welcome to implement the solution too if we find a good one!

**Comment by JadeMaveric** [comment]
Lol, that tweet is word.

One solution is the create a google calendar meet once everything is finalised. And then delete the data on our end. It serves no purpose once the user is done scheduling it. As a bonus, add everyone who voted as a participant in the gCal event. (We'll have to ask for their emails)

The user can then export the event to their prefered calendar and delete it from gCal if they want.

Or, or, we can generate an .ics file that the user downloads and then uploads  to whichever service they use.

**Comment by AnandBaburajan** [comment]
> One solution is the create a google calendar meet once everything is finalised. And then delete the data on our end. It serves no purpose once the user is done scheduling it. As a bonus, add everyone who voted as a participant in the gCal event. (We'll have to ask for their emails)

That's a nice idea, thanks! @anaswaratrajan @BreadGenie @VipinVIP @AthulJoshi @iamAravindks @PushkarDureja @manishprivet @namansamra what do y'all think about this? We're making some changes at https://github.com/RocketMeet/RocketMeet-client/issues/102 so we'll get voters' emails too.

> The user can then export the event to their prefered calendar and delete it from gCal if they want.

:+1:

**Comment by manishprivet** [comment]
Maybe we can create a calendar app, and sync with google Calendar through its apis? I don't think it's a good idea to not store details in the database. Ideally we should be agnostic of calendar services, or we'll be limiting our users to only those who use google Calendar.

**Comment by manishprivet** [comment]
Regarding the tweet, since this is an open source app, we can always provide a self hosting option for people who care about privacy.

**Comment by PushkarDureja** [comment]
> > One solution is the create a google calendar meet once everything is finalised. And then delete the data on our end. It serves no purpose once the user is done scheduling it. As a bonus, add everyone who voted as a participant in the gCal event. (We'll have to ask for their emails)
> 
> That's a nice idea, thanks! @anaswaratrajan @BreadGenie @VipinVIP @AthulJoshi @iamAravindks @PushkarDureja @manishprivet @namansamra what do y'all think about this? We're making some changes at #102 so we'll get voters' emails too.
> 
> > The user can then export the event to their prefered calendar and delete it from gCal if they want.
> 
> 👍

I agree with the part but I think we should only delete the data once we are past the meeting date, So that we could still make use of the invite feature whenever we want (before the event). What do you think ?

**Comment by Aryaman1706** [comment]
Regarding data privacy, I mean we are using google OAuth and Gmail as SMTP. There is no escaping from tech giants like this but I think as far as an app asks me for my information that is already out there like my name and email address, I am fine with that.
I mean the app is helping me be more productive and one tap to login is great to have. The problem arises when the app is asking for permissions far more personal like organizations, contacts, emails, etc, or any write or modify permissions, that is when I grow suspicious of the organization behind the app.
What we can do is we can handle the case when the user denies giving permission for the calendar and allow them to opt-out of the calendar functionality any time they want (I have to check if google allows withdrawing permissions once the user has accepted them) and obviously let them know about this beforehand about what all data we are taking from them. 

As far as the data is concerned I guess we should handle it ourselves and let google handle the bare minimum.

I would love to discuss it further.
Thank You.

**Comment by Aryaman1706** [comment]
> I agree with the part but I think we should only delete the data once we are past the meeting date, So that we could still make use of the invite feature whenever we want (before the event). What do you think ?

I agree. We can run a cron job to do so on a separate thread/container to delete and meanwhile hide any poll whose date has passed. We can make a middleware to check if the actions performed on the poll have a valid date(`poll's date > new Date()`) or not.

**Comment by AnandBaburajan** [comment]
Thank you everyone for your interesting ideas! We would appreciate it if everyone checked our Gitter chatroom. There are some important texts over there - we've a meet coming too to discuss things further! :D

**Comment by AnandBaburajan** [comment]
From the ideas suggested here, we've decided to go forward with [this](https://github.com/RocketMeet/RocketMeet-client/issues/102#issuecomment-796532083) idea - so we'll only store the public polls (for a week or sth before they would be deleted by a cron job). Public and protected polls would be deleted as soon as the invites are sent to attendees (which is yet to be added). And yes, we would be providing a SaaS option to users.

**Comment by AnandBaburajan** [comment]
Please check our Gitter chat for more details.

**Comment by AnandBaburajan** [comment]
We've decided not to delete any polls - we'll simply provide the option to self-host RocketMeet (which is what we suggest too).
