### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [RocketMeet/RocketMeet-client#107]
Hey! I would like to add the following in contributing.md
Add the following -

1. Difference between GIT and GITHUB
2.How to clone,fork repository
3. How to create a branch and then use git push to push to repo
4. Create a PR
5. Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream

I would like to work on this as a part of GSSOC'21

**Comment by AnandBaburajan** [comment]
Hey, thanks for showing interest! But I believe our `contributing.md` has some great resource suggestions like https://opensource.guide/how-to-contribute/ already for beginners. Most of the the points mentioned above are covered in that link and we would prefer if beginners search on Google/SO when they're stuck.
