### ISSUE TITLE
Guided tour for first time users

### ISSUE THREAD

**Issue by JadeMaveric** [RocketMeet/RocketMeet-client#111]
**Is your feature request related to a problem? Please describe.**
The interface felt very ambiguous the first time I visited it. I figured it out eventually, but I feel a simple guided tour would go along way in improving UX. 

**Describe the solution you'd like**
A (skip-able) guided tour that tells the users how to setup their poll. A client-side cookie (or local-storage variable) could be used to check if the current user is a new one)

**Describe alternatives you've considered**
Let users experiment and stare at the screen till they figure it out.

**Comment by AnandBaburajan** [comment]
Hey @JadeMaveric! Thanks for opening this issue and I agree with your points!

**Comment by JadeMaveric** [comment]
Thanks! I'll start working on a PR
