### ISSUE TITLE
Remove table of contents from readme

### ISSUE THREAD

**Issue by AnandBaburajan** [RocketMeet/RocketMeet-client#117]
https://twitter.com/natfriedman/status/1375430850620256257 (^_^")

**Comment by MitanshiKshatriya** [comment]
Can I be assigned on this issue?

**Comment by AnandBaburajan** [comment]
@MitanshiKshatriya Sure you can, but this is a really simple task so we would suggest you to take a bit more challenging ones too.

**Comment by MitanshiKshatriya** [comment]
@AnandBaburajan Yes surely I will, I look forward to working on other issues as well.
