### ISSUE TITLE
Links in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

### ISSUE THREAD

**Issue by akshay1027** [RocketMeet/RocketMeet-client#125]
**Is your feature request related to a problem? Please describe.**
Links in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

**Comment by AnandBaburajan** [comment]
Thanks!

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by AnandBaburajan** [comment]
> Can I work on this issue under GSSoC'21? Kindly assign it to me.

Thanks @AshuKV for showing interest! I think it's better if this issue was taken up by someone who's really new to open source.

**Comment by akshay1027** [comment]
Can I work on this ? @AnandBaburajan

**Comment by AnandBaburajan** [comment]
If you're quite new to open source, find RocketMeet interesting and wish to get started with this issue, yes.

**Comment by akshay1027** [comment]
Thanks!

**Comment by AnandBaburajan** [comment]
> @AnandBaburajan I found in StackOverflow, we can use like this: " [link](URL){:target="_blank"} " to open link in a new tab, but it's not working in GitHub MD file format, can you please tell any other possible solution for this!
> https://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link

Ah, one of the comments mentions that this doesn't work at GitHub (^_^") I don't have any other solutions in mind and I don't think there are any solutions to this. Also this issue isn't that important so maybe we can skip this. If you're interested in working on some other issues, hop on to our Gitter chat and we can discuss your interests!

**Comment by akshay1027** [comment]
Sure thanks! Let me close this one!
