### ISSUE TITLE
Small glitch in 404 page

### ISSUE THREAD

**Issue by VishnuSanal** [RocketMeet/RocketMeet-client#128]
**Describe the bug**

rocketmeet.me/404 <- Here the hyperlink is given to 'homepage', I thing it should be given to 'here' and change 'here's' to 'here is' :)

Plus, we can't recognise the text has a hyperlink

**To Reproduce**
1. Go to rocketmeet.me/404
2. See the bug

**Expected behavior**
Text is changed as expected & the text with hyperlink is underlined as usual :)

**Comment by nishihere19** [comment]
Can I work on this under GSSOC'21?
