### ISSUE TITLE
To add contributor's name in README.md file

### ISSUE THREAD

**Issue by akshatvirmani** [RocketMeet/RocketMeet-client#129]
**Is your feature request related to a problem? Please describe.**
To add contributor's name in README.md file.

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Kindly assign this to me.

**Comment by AnandBaburajan** [comment]
Hey @akshatvirmani! We would prefer if the contributor's names were on our about page, like most other open source projects, We would be happy if you're interested to work on that at #98. Feel free to let us know if you've any doubts. Thanks for showing interest! :)
