### ISSUE TITLE
Better error handling needed

### ISSUE THREAD

**Issue by anaswaratrajan** [RocketMeet/RocketMeet-client#61]
- The app needs better error handling in some pages. 
 For example, there was a network issue that broke the firebase signin popup. But I didn't get a feedback. 
 Similar issues are seen in `/poll/[poll-id]` also.

**Comment by AnandBaburajan** [comment]
>   For example, there was a network issue that broke the firebase signin popup. But I didn't get a feedback.

I got that too. Sometimes the popup closes on its own without letting me login.

**Comment by anaswaratrajan** [comment]
@AnandBaburajan I've handled the network error in #66
