### ISSUE TITLE
UI redesign

### ISSUE THREAD

**Issue by anaswaratrajan** [RocketMeet/RocketMeet-client#62]
- The webapp needs improvements in it's design. 
- It lacks a `features` section and an `about` page 

> According to Krug’s first law of usability, the web-page should be obvious and self-explanatory

- `Footer` 
- `Popovers` on components for first use

**Comment by AnandBaburajan** [comment]
* A row with 3-4 columns (boxes) describing how-to use RocketMeet on the homepage
* Look into properly using `vw`/`rem` for font-sizes and different components

**Comment by AnandBaburajan** [comment]
Currently we don't follow good CSS and Bootstrap practices because of lack of having a dedicated UI/UX dev on our team. So we need to rework on those parts!

**Comment by AnandBaburajan** [comment]
Does anyone recommend https://bulma.io/?

**Comment by AnandBaburajan** [comment]
> > According to Krug’s first law of usability, the web-page should be obvious and self-explanatory
> 
> * `Footer`
> * `Popovers` on components for first use

The footer is being handled at https://github.com/RocketMeet/RocketMeet-client/issues/96.
Guided tour for first time users at https://github.com/RocketMeet/RocketMeet-client/issues/111

**Comment by AnandBaburajan** [comment]
Note that this issue doesn't need to be fixed by a single PR - can be split into multiple smaller PRs.
