### ISSUE TITLE
Show poll count on the homepage

### ISSUE THREAD

**Issue by AnandBaburajan** [RocketMeet/RocketMeet-client#77]
It would be attractive to show the poll count on the homepage. The server's pollCount endpoint can be used for the same.

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by AnandBaburajan** [comment]
> can you please assign this issue to me?

Hi @subhangi2731! We see you're interested in handling quite a lot of issues which is great. But it would be better if you picked just 3 of these for now and leave some of these easy issues to some of the other contributors :) We've some new ideas incoming too! You're also suggested to join our Gitter chatroom too. Let us know at Gitter which 3 you choose to take up first. Thanks!

**Comment by murtaza1112** [comment]
Hey , I am interested in this issue and would like to contribute to it . Can you please assign it me ?

**Comment by AnandBaburajan** [comment]
@murtaza1112 if you're still interested, pls let us know and also share what you plan to do, thanks!

**Comment by murtaza1112** [comment]
I'm really sorry , I got caught with exams for the past few weeks , I'm going through it right now , I'll get it resolved asap .

**Comment by AnandBaburajan** [comment]
> I'm really sorry , I got caught with exams for the past few weeks , I'm going through it right now , I'll get it resolved asap .

Hey, hakuna matata! You don't need to work on this right now! :D you're welcome after exams too! I've just unassigned you for the moment in case there are others interested. Thanks for showing interest! :)

**Comment by shobit1337** [comment]
Hey @AnandBaburajan By homepage you mean on the user's dashboard right?

If no one is currently working on this issue. I would like to try this one!

**Comment by AnandBaburajan** [comment]
> Hey @AnandBaburajan By homepage you mean on the user's dashboard right?

I meant the homepage actually, like "100 polls created so far!" or something. But from our discussions at https://github.com/RocketMeet/RocketMeet-client/issues/106, I think we won't be having this feature in the future. We should have closed this issue! Thanks for showing interest nevertheless! You're welcome to work on other issues!
