### ISSUE TITLE
Add spinner to Invite Button

### ISSUE THREAD

**Issue by VishnuSanal** [RocketMeet/RocketMeet-client#93]
Adding of a spinner to _Send Button_ in _Create Poll Page_ would lead to enhanced UX

**Comment by Amit366** [comment]
Can I work on this issue? I am a GSSOC participant.

Is it like a loading spinner?

**Comment by anaswaratrajan** [comment]
Hi @Amit366. You can work on this. The send button is in `rocketmeet.me/poll/[pollid]`. Just use a loading spinner from [React-bootstrap](https://react-bootstrap.github.io/) until response from mailer is received.

>  If you're a GSSoC participant, only the contributions from March 8 onwards would be counted. You're also suggested to join our Gitter chatroom! The link can be found in our readme. 

https://github.com/RocketMeet/RocketMeet-client/issues/98#issuecomment-791437998

**Comment by Amit366** [comment]
Is it under gasoc? If yes please add the tag

**Comment by AnandBaburajan** [comment]
> Is it under gasoc? If yes please add the tag

We haven't received official instructions on labels yet. I think we'll add them tomorrow after the GSSoC meeting. You're also suggested to join our Gitter chatroom.

**Comment by AnandBaburajan** [comment]
@Amit366 if you're still interested, pls let us know and also share what you plan to do, thanks!

**Comment by Amit366** [comment]
I am having my sem exams. So I don't think I can contribute.

**Comment by AnandBaburajan** [comment]
> I am having my sem exams. So I don't think I can contribute.

Hakuna matata - you're welcome to contribute after your exams too.

**Comment by Amit366** [comment]
Ok thank you

**Comment by AnandBaburajan** [comment]
Closing this since we no longer have the button (the mailer has been deprecated).
