### ISSUE TITLE
Adding of a footer element 

### ISSUE THREAD

**Issue by sidmohanty11** [RocketMeet/RocketMeet-client#96]
for making company look more to the poitn and showing valid information about company?

**Comment by anaswaratrajan** [comment]
@sidmohanty11 We've mentioned the same in #62 along with some other components that we lack and working on it. You are more than welcome to help us! :D

**Comment by RituCs** [comment]
hey, I would like to contribute on this issue.Please assign it to me

**Comment by AnandBaburajan** [comment]
> hey, I would like to contribute on this issue.Please assign it to me

Thanks @RituCs! You're also suggested to join our Gitter chatroom. Link can be found in our readme.
